### ISSUE TITLE
Previous Tarck and Next Track buttons are not working 

### ISSUE THREAD

**Issue by IlManna** [witnessmenow/Spotify-Diy-Thing#14]
Everything work properly except for previous track and next track buttons. I can press them, they turn purple during pressing, but nothing happnes

**Comment by Shizzind** [comment]
I’m having the same problem. (I used the web-flash option to code the CYD, not sure if this issue is related or not)

**Comment by IlManna** [comment]
I tried flashing with Arduino IDE, but I still have the same problem :(

**Comment by IlManna** [comment]
The problem may be related to the fact that Spotify requires a Premium account in order to give skip track functions. I don't own any premium account, so please someone test if with a premium account it's going to work, in order to verify my theory

**Comment by IlManna** [comment]
I found the problem. You need a premium Spotify account in order to have the previous track and next track buttons working.
