### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by sfgrabowski** [witnessmenow/Spotify-Diy-Thing#15]
The photo on the project page shows the screen with a black background with white buttons and text, but the successful fresh install I just made on a CYD has a white background with white text. Is there anyway to invert colours to match the example image?

EDIT: I tried cloning the repo and making the change in Display_Config/User_Setup.h but then when using the local install html it threw up an error "Unable to download manifest" even after I altered the html to point to the correct local file. Is it possible to edit firmware once installed?

EDIT2: Fixed it! Steps to reproduce:

- Install firmware using the web installer & setup as per instructions (Spotify dev account etc)
- Download VSCode for MacOS
- Install platformio IDE
- Clone git
- Point VSCode to folder
- Load platformio.ini
- Edit line 28 so upload_speed = 115200
- Edit line 68 to -DTFT_INVERSION_ON
- Upload code
- Win!

**Comment by witnessmenow** [comment]
Thanks for sharing! Presumably you CYD has two USB ports? The cyd2usb environment on platformio already has the inversion
