### ISSUE TITLE
Inverted colors

### ISSUE THREAD

**Issue by Unster** [witnessmenow/Spotify-Diy-Thing#16]
Hello !

I've installed Spotify DIY on my ESP32-2432S028R / CYD with the web installer and everything works except the colors that are inverted.
My CYD is one with micro-USB + USB-C.

I've tried compiling and installing it with AduinoIDE and I don't manage to make the screen boot at all (but the AP works).

Can someone help me with that ?

Thank you ! :)

**Comment by joalbauer** [comment]
Hi Unster, 
just installed the Diy-Thing with the web flashing tool in chrome under ubuntu. After some trials I finally got it  to work. 
I have the same problem with the inverted colors on the same display (CYD with micro-USB + USB-C). 
Did you ever get it to show the right album art?

**Comment by witnessmenow** [comment]
Use the user_config for the double USB version: https://github.com/witnessmenow/ESP32-Cheap-Yellow-Display/blob/main/DisplayConfig/CYD2USB/User_Setup.h

Or Use platformio :)
