### ISSUE TITLE
PN532 NFC pin connections in readme and nfc.h

### ISSUE THREAD

**Issue by Saschaka** [witnessmenow/Spotify-Diy-Thing#17]
Hi I am confused with the PN532 NFC pin connections. The readme and nfc.h say to connect the sniffer board and the NFC reader on theses pins:

CD to CS
and 
CLK to SCLK

the NFC does not have CS or SCLK labeled though. There is SCL,, SCK and SS, also on the back there is SGCLK. Which ones are right?

This website shows the front pins https://components101.com/wireless/pn532-nfc-rfid-module

Thanks for the amazing project and your open source work

**Comment by witnessmenow** [comment]
SCK == SCLK
CS == SS

Hopefully that should do it!
