### ISSUE TITLE
Create a Webflash page for the project

### ISSUE THREAD

**Issue by witnessmenow** [witnessmenow/Spotify-Diy-Thing#4]
Allow users to [flash this project directly to their ESP32 direct from the browser](https://www.youtube.com/watch?v=xjTACT1qO_8)

Is dependent on #2 and #3

**Comment by witnessmenow** [comment]
Added now

https://witnessmenow.github.io/Spotify-Diy-Thing/WebFlash/

**Comment by unmanagedtn** [comment]
I am having issues with platform IO and I have the 2 port USB version could we get a webflash for that ?
